apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-montage
  namespace: argocd
spec:
  project: video-montage-project
  source:
    repoURL: https://github.com/skorolevskiy/video-montage.git
    targetRevision: main
    path: k8s/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: video-montage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true