apiVersion: v1
kind: Service
metadata:
  name: video-montage-service
  labels:
    app: video-montage
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
    protocol: TCP
    name: http
  selector:
    app: video-montage